config/routes.rb
Rails.application.routes.draw do
  resources :responses do
    post 'save_responses', on: :member
  end
  # resources :questionnaires
  resources :questionnaires do
    post 'save_responses', on: :member
  end
  
  root "questionnaires#index"

  # root to: 'welcome#index'
  get 'welcome/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :questionnaire
  has_many :answers, dependent: :destroy
  has_many :responses
  accepts_nested_attributes_for :answers, allow_destroy: true

  enum question_type: { single_choice: 0, multiple_choice: 1, long_answer: 2 }

  def self.question_type_select
    question_types.keys.map { |k| [k.titleize, k]}
  end
end

app/models/questionnaire.rb
class Questionnaire < ApplicationRecord
    has_many :questions, dependent: :destroy
    has_many :responses, dependent: :destroy
    accepts_nested_attributes_for :questions, allow_destroy: true
end

app/models/response.rb
class Response < ApplicationRecord
  belongs_to :questionnaire
  belongs_to :question
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questionnaires_controller.rb
class QuestionnairesController < ApplicationController
  before_action :set_questionnaire, only: %i[ show edit update destroy ]

  # GET /questionnaires
  def index
    @questionnaires = Questionnaire.all
  end

  # GET /questionnaires/1
  def show
  end

  # GET /questionnaires/new
  def new
    @questionnaire = Questionnaire.new
    @questionnaire.questions.build
  end

  # GET /questionnaires/1/edit
  def edit
  end

  # POST /questionnaires
  def create
    @questionnaire = Questionnaire.new(questionnaire_params)

    if @questionnaire.save
      redirect_to @questionnaire, notice: "Questionnaire was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /questionnaires/1
  def update
    if @questionnaire.update(questionnaire_params)
      redirect_to @questionnaire, notice: "Questionnaire was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /questionnaires/1
  def destroy
    @questionnaire.destroy!
    redirect_to questionnaires_url, notice: "Questionnaire was successfully destroyed."
  end

  def save_responses
    puts '======================================================'
    puts params
    puts '======================================================'

    @questionnaire = Questionnaire.find(params[:id])

    params[:responses]&.each do |question_id, response_text| # 여기서 '&'를 사용하는 이유가 머야?
      question = Question.find(question_id)

      case question.question_type
        when 'multiple_choice'
          selected_answers = response_text.map do |answer_id|
            answer = question.answers.find(answer_id)
            answer.name
          end
          Response.create(questionnaire_id: @questionnaire.id, question_id: question_id, response_text: selected_answers.to_json)

        when 'single_choice'
          answer = question.answers.find(response_text)
          Response.create(questionnaire_id: @questionnaire.id, question_id: question_id, response_text: answer.name)

        when 'long_answer'
          Response.create(questionnaire_id: @questionnaire.id, question_id: question_id, response_text: response_text)
      end
    end

    redirect_to @questionnaire, notice: "Responses saved successfully."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_questionnaire
      @questionnaire = Questionnaire.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def questionnaire_params
      params.require(:questionnaire).permit(
        :name,
        questions_attributes: [
          :_destroy, #얘가 대체 뭘까요?
          :id,
          :question_type,
          :name,
          answers_attributes: [:_destroy, :id, :name]
        ]
      )
    end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
    before_action :set_response, only: %i[ show edit update destroy]

    def index
        @responses = Response.all
    end

    def show
    end

    def new
        @response = Response.new
    end

    def create
        @response = Response.new(response_params)

        respond_to do |format|
            if @response.save
                format.html { redirect_to response_url(@response), notice: "Response was successfully created." }
            else
                format.html { render :new, status: :unprocessable_entity }
            end
        end
    end

    def update
        respond_to do |format|
            if @response.update(response_params)
                format.html { redirect_to response_url(@response), notice: "Response was successfully updated."}
            else
                format.html { render :edit, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        @response.destroy!

        respond_to do |format|
            format.html { redirect_to responses_url, notice: "Response was successfully destroyed."}
        end
    end

    # def save_responses
    #     puts '======================================================'
    #     puts params
    #     puts '======================================================'

    #     questionnaire = Questionnaire.find(params[:questionnaire_id])
    #     puts "questionnaire" + questionnaire
    #     responses = params[:responses]
    #     puts "responses" + responses

    #     ActiveRecord::Base.transaction do
    #         responses.each do |question_id, response|
    #             # For multiple-choice, response is an array of selected answer IDs
    #             if response.is_a?(Array)
    #                 response.each do |answer_id|
    #                     Response.find_or_create_by!(
    #                         questionnaire_id: questionnaire.id,
    #                         question_id: question_id,
    #                         response_text: answer_id
    #                     )
    #                 end
    #             else
    #                 Response.find_or_create_by!(
    #                     questionnaire_id: questionnaire.id,
    #                     question_id: question_id,
    #                     response_text: response
    #                 )
    #             end
    #         end
    #     end

    #     redirect_to questionnaire_path(questionnaire), notice: "Responses were successfully saved."
    # end
    

    private

    def set_response
        @response = Response.find(params[:id])
    end

    def response_params
        params.require(:response).permit(:questionnaire_id, :question_id, :response_text)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light py-4">
  <div class="container-fluid">
    <a class="navbar-brand" href="#" data-config-id="brand">
      <%= image_tag 'logo.png', class: 'img-fluid' %>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nav">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="nav">
      <ul class="d-none d-lg-flex navbar-nav mt-3 mt-lg-0 mb-3 mb-lg-0">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <ul class="navbar-nav mt-3 mt-lg-0 mb-3 mb-lg-0 d-lg-none">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li class="nav-item me-4">
  <%= link_to "Home", root_path, class: 'nav-link' %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuestionnireSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body class='bg-light'>
    <div class="container bg-white border pb-3">
      <%= render 'layouts/navigation' %>
      <% flash.each do |type, msg| %>
        <% if type == 'alert' %>
          <%= content_tag :div, msg, class: "alert alert-danger", role: :alert %>
          <% else %>
          <%= content_tag :div, msg, class: "alert alert-primary", role: :alert %>
        <% end %>
      <% end %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/questionnaires/_answer_fields.html.erb
<div class='nested-fields'>
  <div class='form-group'>
    <%= form.hidden_field :_destroy %>
    <%= form.text_field :name, placeholder: 'Answer', class: 'form-control' %>
    <small>
      <%= link_to "Remove Answer", "#", data: { action: "click->nested-form#remove_association" } %>
    </small>
  </div>
</div>

app/views/questionnaires/_form.html.erb
<%= form_with(model: questionnaire) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div data-controller="nested-form" data-nested-form-index-value="QUESTION_RECORD">
  <!-- 얘는 뭘까요? -->
    <template data-nested-form-target='template'>
      <%= form.fields_for :questions, Question.new, child_index: 'QUESTION_RECORD' do |question| %>
        QUESTION - QUESTION_RECORD
        <%= render 'question_fields', form: question %>
      <% end %>
    </template>

    <%= form.fields_for :questions do |question| %>
      <%= render 'question_fields', form: question %>
    <% end %>

    <div data-nested-form-target="add_item">
      <%= link_to "Add Question", "#", data: { action: "nested-form#add_association" } %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questionnaires/_question_fields.html.erb
<div class='nested-fields box' data-controller='dynamic-select'>
  <div class='form-group'>
    <%= form.select :question_type,
        options_for_select(Question.question_type_select, selected: form.object.question_type),
        {},
        'data-dynamic-select-target': 'select',
        'data-action': 'dynamic-select#selected' %>
  </div>

  <div class='form-group'>
    <%= form.hidden_field :_destroy %>
    <%= form.text_field :name, placeholder: 'Question', class: 'form-control' %>
    <small>
      <%= link_to "Remove", "#", data: { action: "click->nested-form#remove_association" } %>
    </small>
  </div>
  
  <div data-controller="nested-form" data-nested-form-index-value="ANSWER_RECORD" data-dynamic-select-target='choice'>
  <!-- 얘는 또 뭘까요? -->
    <template data-nested-form-target='template'>
      <%= form.fields_for :answers, Answer.new, child_index: 'ANSWER_RECORD' do |answer| %> 
        ANSWER - ANSWER_RECORD
        <%= render 'answer_fields', form: answer %>
      <% end %>
    </template>

    <%= form.fields_for :answers do |answer| %>
      <%= render 'answer_fields', form: answer %>
    <% end %>

    <div data-nested-form-target="add_item">
      <%= link_to "Add Answer", "#", data: { action: "nested-form#add_association" } %>
    </div>
  </div>

  <div data-controller="nested-form" data-dynamic-select-target='long'>
  </div>

</div>

app/views/questionnaires/_questionnaire.html.erb
<div id="<%= dom_id questionnaire %>" class="scaffold_record">
  <p>
    <strong>Name:</strong>
    <%= questionnaire.name %>
  </p>

</div>

app/views/questionnaires/edit.html.erb
<h1>Editing questionnaire</h1>

<%= render "form", questionnaire: @questionnaire %>

<br>

<div>
  <%= link_to "Show this questionnaire", @questionnaire %> |
  <%= link_to "Back to questionnaires", questionnaires_path %>
</div>

app/views/questionnaires/index.html.erb
<h1>Questionnaire</h1>

<table class='table'>
  <thead>
    <th>Name</th>
    
    <th colspan=3>Actions</th>
  </thead>
  <tbody>
    <% @questionnaires.each do |questionnaire| %>
      <tr>
        <td><%= questionnaire.name %></td>
      
        <td><%= link_to "Show", questionnaire_path(questionnaire) %></td>
        <td><%= link_to "Edit", edit_questionnaire_path(questionnaire) %></td>
        <td>
          <%= link_to "Delete", questionnaire_path(questionnaire),
            "data-turbo-method": :delete,
            "data-turbo-confirm": "Are you sure?" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New questionnaire", new_questionnaire_path %>

app/views/questionnaires/new.html.erb
<h1>New questionnaire</h1>

<%= render "form", questionnaire: @questionnaire %>

<br>

<div>
  <%= link_to "Back to questionnaires", questionnaires_path %>
</div>

app/views/questionnaires/show.html.erb
<h1><%= @questionnaire.name %></h1>

<%= form_with url: save_responses_questionnaire_path(@questionnaire), method: :post do |form| %>

  <% @questionnaire.questions.each do |question| %>
    <h2><%= question.name %></h2>

    <% case question.question_type %>
    <% when 'single_choice' %>
      <% question.answers.each do |answer| %>
        <p>
          <%= radio_button_tag "responses[#{question.id}]", answer.id %>
          <%= label_tag "responses[#{question.id}]", answer.name %>
        </p>
      <% end %>
    <% when 'multiple_choice' %>
      <% question.answers.each do |answer| %>
        <p>
          <%= check_box_tag "responses[#{question.id}][]", answer.id %>
          <%= label_tag "responses[#{question.id}][]", answer.name %>
        </p>
      <% end %>
    <% when 'long_answer' %>
      <%= text_area_tag "responses[#{question.id}]"%>
    <% end %>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

<!--

이런 방식으로 문제를 해결해야 하는 것인가?
https://github.com/jerico-digiteer/questionnaire/blob/main/app/views/questionnaires/show.html.slim

-->

app/views/responses/_form.html.erb
<%= form_with(model: response) do |form| %>
  <div class="field">
    <%= form.label :questionnaire_id, "Questionnaire" %>
    <%= form.collection_select :questionnaire_id, Questionnaire.all, :id, :name, prompt: "Select a Questionnaire" %>
  </div>

  <div class="field">
    <%= form.label :question_id, "Question" %>
    <%= form.collection_select :question_id, Question.where(questionnaire_id: response.questionnaire_id), :id, :name, prompt: "Select a Question" %>
  </div>

  <div class="field">
    <%= form.label :response_text, "Response" %>
    <%= form.text_area :response_text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/responses/_response.html.erb
<div id="<%= dom_id response %>" class="scaffold_record">
  <p>
    <strong>Questionnaire:</strong>
    <%= response.questionnaire_id %>
  </p>

  <p>
    <strong>Question:</strong>
    <%= response.question_id %>
  </p>

  <p>
    <strong>Response text:</strong>
    <%= response.response_text %>
  </p>
</div>

app/views/responses/edit.html.erb
<h1>Edit Response</h1>

<%= render "form", response: @response %>

<br>

<div>
  <%= link_to "Back to responses", responses_path %>
</div>

app/views/responses/index.html.erb
<h1>Responses</h1>

<table class='table'>
  <thead>
    <tr>
        <th>Questionnaire</th>
        <th>Question</th>
        <th>Response</th>
        <th colspan=3>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @responses.each do |response| %>
      <tr>
        <td><%= response.questionnaire.name %></td>
        <td><%= response.question.name %></td>
        <td><%= response.response_text %></td>
      
        <td><%= link_to "Show", response_path(response) %></td>
        <td><%= link_to "Edit", edit_response_path(response) %></td>
        <td>
          <%= link_to "Delete", response_path(response),
            "data-turbo-method": :delete,
            "data-turbo-confirm": "Are you sure?" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "Go to Surveys", questionnaires_path %>

app/views/responses/new.html.erb
<h1>New Response</h1>

<%= render "form", response: @response %>

<br>

<div>
  <%= link_to "Back to responses", responses_path %>
</div>

app/views/responses/show.html.erb
<h1>Response Details</h1>

<p>
  <strong>Questionnaire:</strong>
  <%= @response.questionnaire.name %>
</p>

<p>
  <strong>Question:</strong>
  <%= @response.question.name %>
</p>

<p>
  <strong>Response:</strong>
  <%= @response.response_text %>
</p>

<div>
  <%= link_to "Back to responses", responses_path %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>